// Generated by https://quicktype.io

export interface AsignacionComputador {
  id:           string;
  location:     string;
  observations: null | string;
  userPc:       string;
  password:     string;
  anydeskCode:  string;
  status:       string;
  userId:       string;
  computerId:   string;
  printerId:    null | string;
  computer:     ComputadorAsignado;
  printer:      ImpresoraAsignada | null;
  userCuid:     FuncionarioAsignado;
}

export interface ComputadorAsignado {
  id:          string;
  brand:       string;
  model:       string;
  serial:      string;
  processor:   string;
  ram:         number;
  storage:     number;
  os:          string;
  peripherals: string[];
  type:        string;
  status:      string;
  imageId:     string;
}

export interface ImpresoraAsignada {
  id:         string;
  brand:      string;
  model:      string;
  serial:     string;
  inkDetails: string;
  type:       string;
  status:     string;
  imageId:    string;
} 

export interface FuncionarioAsignado {
  id:         string;
  fullName:   string;
  email:      string;
  phone:      string;
  dependency: string;
}
