// Generated by https://quicktype.io

export interface Impresora {
  id:         string;
  brand:      string;
  model:      string;
  serial:     string;
  inkDetails: string;
  type:       string;
  status:     string;
  imageId:    string;
  imageRel:   ImageImpresora;
}

export interface ImageImpresora {
  id:           string;
  cloudinaryId: string;
  secureUrl:    string;
}
